### PR TITLE
Bring up-to-date for intercom 3

### PR DESCRIPTION
**Pull request by MarkMurphy**
This pull request renames `custom_data` to `custom_attributes` and  addresses several other pull-requests as well:
- https://github.com/intercom/intercom-rails/pull/125
- https://github.com/intercom/intercom-rails/pull/124
- https://github.com/intercom/intercom-rails/pull/114
- https://github.com/intercom/intercom-rails/pull/102

### CODE REVIEW

**Comment by MarkMurphy** [comment]
This pull request renames `custom_data` to `custom_attributes` and  addresses several other pull-request as well:

- https://github.com/intercom/intercom-rails/pull/125
- https://github.com/intercom/intercom-rails/pull/124
- https://github.com/intercom/intercom-rails/pull/114
- https://github.com/intercom/intercom-rails/pull/102

**Comment by frobichaud** [comment]
@MarkMurphy you're missing a required change in railtie.rb, line 5 should be CustomAttributesHelper instead of CustomDataHelper

**Comment by frobichaud** [comment]
@MarkMurphy there are other several issues with this PR, such as setting the Accept header and avoiding to JSON.parse the response.body when there are no errors. 
See my changes in my master branch of https://github.com/petaldevelopment/intercom-rails and compare with MarkMurphy:intercom-3

**Comment by frobichaud** [comment]
See:
https://github.com/MarkMurphy/intercom-rails/pull/2

**Comment by Skaelv** [comment]
How annoying is it for you to use `custom_data` methods instead of `custom_attributes` ? 
I'm not sure we want to introduce breaking changes because of a method name change.

**Pull request closed without merging**
