### PR TITLE
Make use of ActiveSupport lazy loading

### PR DESCRIPTION
**Pull request by koenpunt**
this to prevent load order issues. 
More on lazy loading here: https://simonecarletti.com/blog/2011/04/understanding-ruby-and-rails-lazy-load-hooks/

### CODE REVIEW

**Comment by koenpunt** [comment]
Ping ✨

**Comment by attenzione** [comment]
could it be possible fix for #235?

**Comment by koenpunt** [comment]
@mmartinic can you please take a look at this?

**Comment by mmartinic** [comment]
@koenpunt Thanks for the PR!

**Comment by lucascaton** [comment]
Hi there. When is it going to be released? Cheers.

**Pull request merged**
