### PR TITLE
add hide_intercom_messenger_for_request

### PR DESCRIPTION
**Pull request by mmartinic**

### CODE REVIEW

**Comment by attenzione** [comment]
this can be done through 
```skip_after_action :intercom_rails_auto_include, only: [:show]```

**Comment by jfeust** [comment]
@attenzione That doesn't seem to work with turbolinks 5 enabled. If you load a page without the skip_after_action, the JS stays loaded on the page you're trying to do the skip_after_action.  I'm not sure this PR is the right answer, but we're also having trouble with turbolinks and supressing the intercom messenger on certain actions.

**Comment by jfeust** [comment]
Update, I'm now doing this by setting a custom data attribute in the controller actions where I want to hide it: `intercom_custom_data.user[:hide_default_launcher] = true`

**Comment by eoin** [comment]
Closing in favor of [using `skip_after_action`](https://github.com/intercom/intercom-rails#disabling-automatic-insertion).

**Pull request closed without merging**
